language: python

branches:
  only:
  - master

# We now support osx and linux (not windows due to dependencies)
# python versions are 3.6+
# we run the kitchen sink build and a minimal viable build
matrix:
  include:
  # Test osx with everything
  - os: osx
    language: generic
    env:
      - PYTHON_VER=3.6
      - ENV=EVERYTHING
  - os: osx
    language: generic
    env:
      - PYTHON_VER=3.7
      - ENV=EVERYTHING

  # Test Linux with everything
  - os: linux
    python: 3.6
    env:
      - PYTHON_VER=3.6
      - ENV=EVERYTHING
  - os: linux
    python: 3.7
    env:
      - PYTHON_VER=3.7
      - ENV=EVERYTHING

  # Test Linux with minimal
  - os: linux
    python: 3.6
    env:
      - PYTHON_VER=3.6
      - ENV=MINIMAL
  - os: linux
    python: 3.7
    env:
      - PYTHON_VER=3.7
      - ENV=MINIMAL

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environemt
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - |
    if [ $ENV == "EVERYTHING" ]; then
      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/everything.yaml
    elif [ $ENV == "MINIMAL" ]; then
      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/minimal.yaml
    else
      echo "ERROR: No match for PROG ($ENV)."
      exit 1
    fi
  - source activate test

  # Build and install package
  - python setup.py develop --no-deps

script:
  # we need to sort this so only the relevant tests run on the right builds, do not test missing packages
  # first make sure qubekit is installed by testing the entry points
  - QUBEKit -h
  - qubekit -h
  # now run tests
  - python QUBEKit/tests/ligand_tests.py

notifications:
  email: false
